[tool.poetry]
name = "fundermapssdk"
version = "0.1.0"
description = ""
authors = ["Yorick de Wid <yorickdewid@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"
psycopg2-binary = "^2.9.9"
colorlog = "^6.8.2"

[tool.poetry.scripts]
load_bag = "load_bag:main"
refresh_models = "refresh_models:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
